[Setup]
AppName=Kaalen Data Viewer
AppVersion=1.0
AppPublisher=Mathesh Vaithiyanathan
DefaultDirName={autopf}\Kaalen
DefaultGroupName=Kaalen
AllowNoIcons=yes
OutputDir=Output_Installer
OutputBaseFilename=Kaalen_Setup_v1.0
Compression=lzma
SolidCompression=yes
SetupIconFile=icon.ico
WizardStyle=modern
RestartIfNeededByRun=yes
AppId=Kaalen_Data_Viewer
UninstallDisplayIcon={app}\Kaalen_App.exe
VersionInfoVersion=1.0.0
VersionInfoCompany=Mathesh Vaithiyanathan
PrivilegesRequired=admin
